"""Built-in resource plugins. Importing this package registers them all."""

from pyecsdwan.resources import (
    appliance_zones,
    bgp,
    deployment,
    dhcp,
    interface_labels,
    internal_subnets,
    loopback,
    nat,
    ospf,
    overlays,
    policy_maps,
    priorities,
    regions,
    routes,
    security_policy,
    shapers,
    templates,
    vrrp,
    zones,
)

__all__ = [
    "appliance_zones",
    "bgp",
    "deployment",
    "dhcp",
    "interface_labels",
    "internal_subnets",
    "loopback",
    "nat",
    "ospf",
    "overlays",
    "policy_maps",
    "priorities",
    "regions",
    "routes",
    "security_policy",
    "shapers",
    "templates",
    "vrrp",
    "zones",
]
